name: Debian image - x86_64

on:
  push:
  pull_request:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  build-custom-image-job:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out AOSP code
      run: git clone https://android.googlesource.com/platform/packages/modules/Virtualization -b main
    - name: build the image
      run: sudo ./Virtualization/build/debian/build.sh -a x86_64
    - name: Publish the artifiacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # aka v4.0.0
      with:
        name: artifacts
        path: images.tar.gz
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        tag_name: release_x86_64
        files: |
          images.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
