name: Debian image - aarch64

on:
  push:
  pull_request:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  build-custom-image-job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out AOSP code
      run: git clone https://android.googlesource.com/platform/packages/modules/Virtualization -b main
    - name: build the image
      run: sudo ./Virtualization/build/debian/build.sh
    - name: Publish the artifiacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # aka v4.0.0
      with:
        name: image
        path: image.raw
